
CREATE TABLE IF NOT EXISTS `answer_comment` (
  `ID_COMMENT` int(11) DEFAULT NULL,
  `ANSWER_COMMENT` text,
  `ANICKNAME` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `characteristic` (
  `ID_PRODUCT` int(11) DEFAULT NULL,
  `DENOMINATION` varchar(50) DEFAULT NULL,
  `CONTENT` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `comment` (
  `NICKNAME` varchar(60) DEFAULT NULL,
  `COMMENT` text,
  `ID_PRODUCT` int(11) DEFAULT NULL,
  `ID_COMMENT` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_COMMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `product` (
  `ID_PRODUCT` int(11) NOT NULL,
  `NAME_PRODUCT` varchar(100) NOT NULL,
  `DESCRIBE` text NOT NULL,
  `ID_CATEGORY` int(11) NOT NULL,
  `IMAGE` varchar(30) DEFAULT NULL,
  `PRICE` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUCT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `product_category` (
  `ID_CATEGORY` int(11) NOT NULL,
  `NAME_PARENT_CATEGORY` int(11) NOT NULL,
  `NAME_CATEGORY` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `product_parrent_category` (
  `NAME_PARENT_CATEGORY` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user` (
  `NICKNAME` varchar(30) NOT NULL,
  `FIRSTNAME` varchar(30) DEFAULT NULL,
  `LASTNAME` varchar(30) DEFAULT NULL,
  `GENDER` enum('М','Ж') DEFAULT NULL,
  `RANK` enum('ADMIN','USER') DEFAULT NULL,
  `PASSWORD` char(32) DEFAULT NULL,
  `SECOND_NAME` varchar(60) DEFAULT NULL,
  `EMAIL` varchar(60) DEFAULT NULL,
  `TOKEN` char(100) DEFAULT NULL,
  PRIMARY KEY (`NICKNAME`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
